---
title: "R and RStudio for Statistics"
format:
  html:
    theme: cosmo
    smooth-scroll: true
---

This site hosts my course notes, presentations and data files accompanying my courses on R and RStudio.  

There are also some general notes on statistics that I have created for myself (for exploring different ideas) or to help others.

* NBI/JIC MSc Introduction to R
    * [Day 1](day1.qmd)
    * [Day 2/3 (PhD version)](day2.qmd)
    * [Day 3 (MSc version)](day3msc.qmd)
* How many samples do I need?
    * [Course notes](sampleSize.qmd)
* Statistics notes
    * [A note on graphing](day3.qmd)
    * [Don't dichotomise your data](dichot.qmd)
    * [Simple alpha and beta diversity simulation](alphabeta.qmd)
    * [Selection bias (Berkson bias) in observational studies](berkson.qmd)
    * [Sampling from clustered data in observational studies](independentclusters.qmd)
    * [Run bigger experiments instead of internal replications of smaller experiments](repeats.qmd)
* Notes on using R
    * [Tidyverse, data.table and others for making descriptive tables](datatabletidyverse.qmd)
    * [Using packages, functions and pipes](praise.qmd)
    * [An analysis of the Iris dataset](irisScript.qmd)

Older stuff

* JIC MSc Workshop (2021/2022)
    * [Tutorial](workshopscript.html)